# Generated by Django 4.2.1 on 2023-05-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
